env:
  browser: true
  es6: true
  node: true
extends: 
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
  sourceType: module
plugins:
  - react
rules:
  sort-imports:
    - warn
    - ignoreCase: false
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - single
        - multiple
  no-console:
    - warn
globals:
  describe: true
  it: true
  expect: true
  jest: true
  beforeEach: true
