env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
  sourceType: module
plugins:
  - react
rules:
  no-undef:
    - off
  no-unused-vars:
    - warn
  no-console:
    - warn
  indent:
    - warn
    - tab
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
